### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by baoc2** [Ghostir/twitch-go#1]
Hi, I'm having this issue that I'm stuck with the "Authenticate with Twitch" screen.
Every time I restart my browser I'll be allowed to navigate to the login screen where it asks me for my username and password followed by the 2FA authentication.
After I've done the above my Twitch Go will still be at the "Authenticate with Twitch" screen, but this time if I click on the button there will only be an instant pop-up that I assume is the login screen again but prolly skipped as I'm supposed to be logged in.
The reset twitch token hyperlink also doesn't take me anywhere.

As a result, I'm basically stuck with the "Authenticate with Twitch" screen, do you know what might be causing this and how can I solve it?

I'm using Microsoft Edge on my Macbook Pro, but switching to Chrome also has this issue.

**Comment by baoc2** [comment]
Dammit, it fixed itself after a few minutes...
Sorry to bother.

**Comment by Ghostir** [comment]
Glad the issue was resolved, sometimes it takes a few minutes for Twitch to give access to the Extension.

I'm glad you were able to figure it out though! Let me know if you have any feedback or suggestions. I'm currently rolling out a nice and refreshing update to the UI and Sections of the Extension. 

I'm always open to suggestions since this is mainly for the community and would love to make something everyone enjoys.
